Style/FrozenStringLiteralComment:
  Enabled: false

# メソッドの接頭辞にget_とかset_とかつけないルール
# すでにつけっちゃってて面倒とかだとfalseにする
Naming/AccessorMethodName:
  Enabled: false

# gemの並びを名前順にするもの
# すでにバラバラで修正面倒だと変にいじるとこわいのでfalseにする
Bundler/OrderedGems:
  Enabled: false

Naming/PredicateName:
  Enabled: false

# 複数行の場合はケツカンマを入れる(Arrayリテラル)
Style/TrailingCommaInArrayLiteral:
  Enabled: false
  # EnforcedStyleForMultiline: comma

# 複数行の場合はケツカンマを入れる(Hashリテラル)
# => 気持ち悪いので無効化
Style/TrailingCommaInHashLiteral:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25 

Metrics/ParameterLists:
  Enabled: false
 
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/AsciiComments:
  Enabled: false


# classの上にコメントつけなさいエラーを回避
Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
