language: ruby
rvm: 2.5.3
services:
  - mysql
  - redis-server
bundler_args: "--without development --jobs=3"
cache: bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - rails db:create
  - rails db:migrate
  #- bundle exec rake db:setup
